import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { nanoid } from "nanoid";
import type { AspectRatioValue, MediaAsset } from "@dasd/higg-shared";

/**
 * The media store: generated bytes are written under `<server>/media/`
 * (gitignored) as `<assetId>.<ext>` and served back through `/api/media/...`.
 * Provider adapters call `writeMedia`; the media route calls `readMedia`; the
 * generate route uses the data-URL helpers to feed reference images to Gemini.
 */

const moduleDir = path.dirname(fileURLToPath(import.meta.url));
// moduleDir = <server>/src/store → files live at <server>/media (gitignored).
const MEDIA_DIR = path.join(moduleDir, "..", "..", "media");

const EXT_BY_MIME: Record<string, string> = {
  "image/svg+xml": "svg",
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/webp": "webp",
  "image/gif": "gif",
  "video/mp4": "mp4",
  "video/webm": "webm",
};

const MIME_BY_EXT: Record<string, string> = {
  svg: "image/svg+xml",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  webp: "image/webp",
  gif: "image/gif",
  mp4: "video/mp4",
  webm: "video/webm",
};

function extForMime(mimeType: string): string {
  return EXT_BY_MIME[mimeType] ?? "bin";
}

function mimeForExt(ext: string): string {
  return MIME_BY_EXT[ext.toLowerCase()] ?? "application/octet-stream";
}

export interface WriteMediaInput {
  bytes: Uint8Array;
  mimeType: string;
  width?: number;
  height?: number;
}

/** Persist bytes and return the `MediaAsset` describing where they now live. */
export function writeMedia(input: WriteMediaInput): MediaAsset {
  mkdirSync(MEDIA_DIR, { recursive: true });
  const assetId = nanoid();
  const file = `${assetId}.${extForMime(input.mimeType)}`;
  writeFileSync(path.join(MEDIA_DIR, file), input.bytes);
  return {
    assetId,
    url: `/api/media/${file}`,
    mimeType: input.mimeType,
    width: input.width,
    height: input.height,
  };
}

/** Read a stored file by its bare `<assetId>.<ext>` name (path-traversal safe). */
export function readMedia(file: string): { bytes: Uint8Array; mimeType: string } | null {
  const safe = path.basename(file);
  if (safe.length === 0 || safe !== file) return null;
  try {
    const bytes = readFileSync(path.join(MEDIA_DIR, safe));
    const ext = path.extname(safe).replace(/^\./, "");
    return { bytes: new Uint8Array(bytes), mimeType: mimeForExt(ext) };
  } catch {
    return null;
  }
}

/** Decode a `data:<mime>;base64,<payload>` (or plain-text) URL into bytes. */
export function dataUrlToBytes(dataUrl: string): { bytes: Uint8Array; mimeType: string } | null {
  const match = /^data:([^;,]*)(;base64)?,([\s\S]*)$/.exec(dataUrl);
  if (!match) return null;
  const mimeType = match[1] && match[1].length > 0 ? match[1] : "application/octet-stream";
  const isBase64 = Boolean(match[2]);
  const payload = match[3] ?? "";
  const bytes = isBase64
    ? new Uint8Array(Buffer.from(payload, "base64"))
    : new Uint8Array(Buffer.from(decodeURIComponent(payload), "utf8"));
  return { bytes, mimeType };
}

/** Store an array of data URLs, skipping any that fail to decode. */
export function storeDataUrls(urls: string[]): MediaAsset[] {
  const assets: MediaAsset[] = [];
  for (const url of urls) {
    const decoded = dataUrlToBytes(url);
    if (!decoded) continue;
    assets.push(writeMedia({ bytes: decoded.bytes, mimeType: decoded.mimeType }));
  }
  return assets;
}

function bytesToDataUrl(bytes: Uint8Array, mimeType: string): string {
  return `data:${mimeType};base64,${Buffer.from(bytes).toString("base64")}`;
}

/** Load a stored asset (by id, extension unknown) as a base64 data URL. */
export function readMediaAsDataUrl(assetId: string): string | null {
  let file: string | undefined;
  try {
    file = readdirSync(MEDIA_DIR).find((f) => f.startsWith(`${assetId}.`));
  } catch {
    return null;
  }
  if (!file) return null;
  const media = readMedia(file);
  return media ? bytesToDataUrl(media.bytes, media.mimeType) : null;
}

/**
 * Normalise a reference (data URL or a local `/api/media/...` URL) into a data
 * URL a provider can embed inline. Unknown/remote URLs are dropped (returns null).
 */
export function referenceToDataUrl(ref: string): string | null {
  if (ref.startsWith("data:")) return ref;
  const prefix = "/api/media/";
  if (ref.startsWith(prefix)) {
    const media = readMedia(ref.slice(prefix.length));
    return media ? bytesToDataUrl(media.bytes, media.mimeType) : null;
  }
  return null;
}

/** Pixel dimensions for an aspect ratio, longest side normalised to 1024. */
export function aspectSize(aspectRatio: AspectRatioValue): { width: number; height: number } {
  const parts = aspectRatio.split(":");
  const w = Number(parts[0] ?? "1") || 1;
  const h = Number(parts[1] ?? "1") || 1;
  const base = 1024;
  return w >= h
    ? { width: base, height: Math.round((base * h) / w) }
    : { width: Math.round((base * w) / h), height: base };
}
