import type { CameraPreset } from "@dasd/higg-shared";

/**
 * A curated preset library — the "director of photography" abstraction. Each
 * preset is one button that composes into a prompt via `promptSuffix` (appended
 * for prompt-driven video/image backends). Camera moves plus a couple of VFX /
 * transition looks. Stable slug-based ids so a saved `presetId` keeps resolving.
 */
export const PRESETS: CameraPreset[] = [
  {
    id: "crash-zoom-in",
    slug: "crash-zoom-in",
    name: "Crash Zoom In",
    category: "camera",
    motionType: "zoom",
    description: "A violent snap zoom that slams onto the subject for instant impact.",
    intensity: 0.9,
    speed: 0.95,
    promptSuffix: "aggressive crash zoom in onto the subject, sudden punch-in, motion blur streaks",
    examplePrompt: "a lone samurai turning to face the camera",
    tags: ["punchy", "impact", "zoom"],
  },
  {
    id: "dolly-in",
    slug: "dolly-in",
    name: "Dolly In",
    category: "camera",
    motionType: "dolly",
    description: "A smooth push toward the subject that builds intimacy and focus.",
    intensity: 0.5,
    speed: 0.45,
    promptSuffix:
      "slow cinematic dolly in, camera gliding toward the subject, shallow depth of field",
    examplePrompt: "a detective studying a wall of clues",
    tags: ["smooth", "push-in", "cinematic"],
  },
  {
    id: "dolly-out",
    slug: "dolly-out",
    name: "Dolly Out",
    category: "camera",
    motionType: "dolly",
    description: "A gliding pull-back that reveals scale and context around the subject.",
    intensity: 0.5,
    speed: 0.45,
    promptSuffix: "slow cinematic dolly out, camera pulling back to reveal the wider scene",
    examplePrompt: "a figure standing at the edge of a vast canyon",
    tags: ["reveal", "pull-back", "cinematic"],
  },
  {
    id: "360-orbit",
    slug: "360-orbit",
    name: "360 Orbit",
    category: "camera",
    motionType: "orbit",
    description: "A full circular orbit around the subject for a hero, product-reveal feel.",
    intensity: 0.7,
    speed: 0.6,
    promptSuffix:
      "smooth 360 degree orbit around the subject, camera circling, parallax on the background",
    examplePrompt: "a futuristic motorcycle in an empty showroom",
    tags: ["orbit", "hero", "product"],
  },
  {
    id: "bullet-time",
    slug: "bullet-time",
    name: "Bullet Time",
    category: "camera",
    motionType: "bullet_time",
    description: "Time freezes while the camera arcs around a suspended moment.",
    intensity: 0.85,
    speed: 0.3,
    promptSuffix:
      "bullet-time effect, frozen moment in time, camera arcing around the subject, suspended particles",
    examplePrompt: "a dancer mid-leap surrounded by shattering glass",
    tags: ["slow-mo", "frozen", "matrix"],
  },
  {
    id: "fpv-drone",
    slug: "fpv-drone",
    name: "FPV Drone",
    category: "camera",
    motionType: "fpv",
    description: "A fast, weaving first-person drone flight that dives through the scene.",
    intensity: 0.9,
    speed: 0.9,
    promptSuffix:
      "high-speed FPV drone shot weaving through the scene, diving and banking, wide-angle lens",
    examplePrompt: "a neon alleyway packed with market stalls",
    tags: ["fast", "drone", "immersive"],
  },
  {
    id: "crane-up",
    slug: "crane-up",
    name: "Crane Up",
    category: "camera",
    motionType: "crane",
    description: "A rising crane move that lifts up and away for an epic establishing beat.",
    intensity: 0.6,
    speed: 0.5,
    promptSuffix:
      "sweeping crane shot rising up and away from the subject, revealing the landscape below",
    examplePrompt: "a knight standing before a besieged castle",
    tags: ["epic", "rise", "establishing"],
  },
  {
    id: "whip-pan",
    slug: "whip-pan",
    name: "Whip Pan",
    category: "camera",
    motionType: "pan",
    description: "A fast blurred horizontal swipe — great as a snappy transition move.",
    intensity: 0.85,
    speed: 0.95,
    promptSuffix: "fast whip pan, heavy horizontal motion blur, energetic camera swipe",
    examplePrompt: "a chef plating a dish in a busy kitchen",
    tags: ["fast", "transition", "energetic"],
  },
  {
    id: "handheld",
    slug: "handheld",
    name: "Handheld",
    category: "camera",
    motionType: "handheld",
    description: "Loose, breathing handheld motion for a raw, documentary-style feel.",
    intensity: 0.4,
    speed: 0.4,
    promptSuffix: "handheld camera, subtle organic shake, documentary realism, natural motion",
    examplePrompt: "a musician tuning a guitar backstage",
    tags: ["raw", "documentary", "organic"],
  },
  {
    id: "vertigo",
    slug: "vertigo",
    name: "Vertigo (Dolly Zoom)",
    category: "camera",
    motionType: "zoom",
    description: "The dolly-zoom illusion: background warps while the subject stays fixed.",
    intensity: 0.8,
    speed: 0.5,
    promptSuffix:
      "vertigo dolly-zoom effect, background stretching and warping while the subject stays fixed",
    examplePrompt: "a person frozen at the top of a staircase",
    tags: ["dolly-zoom", "unsettling", "hitchcock"],
  },
  {
    id: "snorricam",
    slug: "snorricam",
    name: "SnorriCam",
    category: "camera",
    motionType: "handheld",
    description: "Rig-mounted to the subject: they stay locked while the world swirls behind.",
    intensity: 0.75,
    speed: 0.6,
    promptSuffix:
      "SnorriCam body-mounted shot, subject locked centre-frame while the background sways and spins",
    examplePrompt: "a man running panicked through a crowd",
    tags: ["disorienting", "subjective", "body-mount"],
  },
  {
    id: "super-dolly",
    slug: "super-dolly",
    name: "Super Dolly",
    category: "camera",
    motionType: "dolly",
    description: "A relentless, ultra-smooth high-speed push straight down the axis.",
    intensity: 0.8,
    speed: 0.85,
    promptSuffix:
      "super dolly, ultra-smooth high-speed push straight toward the subject on a fixed axis",
    examplePrompt: "a doorway glowing at the end of a long corridor",
    tags: ["smooth", "fast", "push-in"],
  },
  {
    id: "explosion",
    slug: "explosion",
    name: "Explosion",
    category: "vfx",
    motionType: "handheld",
    description: "A fiery blast with debris, sparks, and a shockwave rippling outward.",
    intensity: 0.95,
    speed: 0.9,
    promptSuffix:
      "massive fiery explosion, flying debris and sparks, shockwave and rolling smoke, camera shake",
    examplePrompt: "a car in the middle of a desert road",
    tags: ["vfx", "fire", "action"],
  },
  {
    id: "light-leak-transition",
    slug: "light-leak-transition",
    name: "Light Leak Transition",
    category: "transition",
    motionType: "pan",
    description: "A warm analog light-leak wash that flares across to bridge two shots.",
    intensity: 0.6,
    speed: 0.7,
    promptSuffix:
      "warm analog light-leak transition, lens flare washing across the frame, dreamy bloom",
    examplePrompt: "sunlight spilling over a field of tall grass",
    tags: ["vfx", "transition", "analog"],
  },
];
